/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier:  BSD-3-Clause
*/
#include <stdio.h>
#include "common_utils.h"
#include "main_application.h"
// Uncomment the desired debug level
#include "log_disabled.h"
//#include "log_error.h"
//#include "log_warning.h"
//#include "log_info.h"
//#include "log_debug.h"

void main_application(void) {
// Start of autogenerated code
  while(true) {
    utils_set_LED(LED3_LED, BSP_IO_LEVEL_HIGH);
    utils_delay_ms(250);
    utils_set_LED(LED2_LED, BSP_IO_LEVEL_HIGH);
    utils_delay_ms(250);
    utils_set_LED(LED1_LED, BSP_IO_LEVEL_HIGH);
    utils_delay_ms(250);
    utils_set_LED(LED3_LED, BSP_IO_LEVEL_LOW);
    utils_delay_ms(250);
    utils_set_LED(LED2_LED, BSP_IO_LEVEL_LOW);
    utils_delay_ms(250);
    utils_set_LED(LED1_LED, BSP_IO_LEVEL_LOW);
    utils_delay_ms(250);
  }
// End of autogenerated code

}

